apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeshift-starters--devfile-sample-xbhk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeshift-starters--devfile-sample-xbhk
    app.kubernetes.io/part-of: nodeshift-starters--devfile-sample
  name: nodeshift-starters--devfile-sample-xbhk
  namespace: siwinski1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodeshift-starters--devfile-sample-xbhk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodeshift-starters--devfile-sample-xbhk
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:426d1333be8a271bbc6bf1f09f0de49c3d528a3dbd2b541de329c02f3a2fea3a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
