apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeshift-starters--devfile-sample-xbhk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeshift-starters--devfile-sample-xbhk
    app.kubernetes.io/part-of: nodeshift-starters--devfile-sample
  name: nodeshift-starters--devfile-sample-xbhk
  namespace: siwinski1-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: nodeshift-starters--devfile-sample-xbhk
    weight: null
status: {}
