apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeshift-starters--devfile-sample-xbhk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeshift-starters--devfile-sample-xbhk
    app.kubernetes.io/part-of: nodeshift-starters--devfile-sample
  name: nodeshift-starters--devfile-sample-xbhk
  namespace: siwinski1-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodeshift-starters--devfile-sample-xbhk
status:
  loadBalancer: {}
